version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - voting
  voting_app:
    image: robertsilvatech/py-voting-app
    ports:
      - "8000:8000"
    networks:
      - voting

networks:
   voting:

